# Generated by Django 3.1.2 on 2020-11-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='sal',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='uname',
        ),
    ]
