# Generated by Django 3.2.3 on 2021-05-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_model',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
