# Generated by Django 3.2.3 on 2021-05-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_profile_model_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='phone',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
