# Generated by Django 3.1.2 on 2020-11-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('skill', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Applied', max_length=120)),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='contact',
            field=models.IntegerField(default=9999999999),
        ),
    ]
