# Generated by Django 3.1.2 on 2020-11-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=120)),
                ('ingredients', models.CharField(max_length=220)),
                ('category', models.CharField(max_length=80)),
            ],
        ),
    ]
