# Generated by Django 3.1.2 on 2020-11-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=120)),
                ('hourlyRate', models.ImageField(upload_to='')),
                ('skillset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institution.skills')),
            ],
        ),
    ]
