# Generated by Django 3.1.2 on 2020-11-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20201119_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=120)),
                ('visitingtime', models.DateField(null=True)),
            ],
        ),
    ]
