# Generated by Django 3.1.2 on 2020-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
