# Generated by Django 3.1.2 on 2021-01-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('bill_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('buying_price', models.IntegerField(default=1)),
                ('selling_price', models.IntegerField(default=10)),
                ('date', models.DateField(auto_now=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.salesmodel')),
            ],
        ),
    ]
