# Generated by Django 3.1.2 on 2021-01-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_auto_20210106_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmodel',
            name='bill_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
