# Generated by Django 3.1.2 on 2021-01-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0007_auto_20210106_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.productmodel'),
        ),
    ]
