# Generated by Django 3.1.2 on 2021-01-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0009_auto_20210110_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='bill_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.salesmodel'),
        ),
    ]
