# Generated by Django 3.1.2 on 2021-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0011_auto_20210111_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
