# Generated by Django 3.1.2 on 2021-08-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_project', models.CharField(max_length=50, unique=True)),
                ('str_project_code', models.CharField(max_length=50, unique=True)),
                ('int_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelWorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_workstatus', models.CharField(max_length=50)),
                ('str_workstatus_code', models.CharField(max_length=50)),
                ('int_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelWorkTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_worktype', models.CharField(max_length=50)),
                ('int_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_title', models.CharField(max_length=50)),
                ('txt_description', models.TextField(max_length=200)),
                ('jsn_attachment', models.JSONField(blank=True, null=True)),
                ('dbl_estimatation', models.FloatField(blank=True, null=True)),
                ('dat_start', models.DateField(blank=True, null=True)),
                ('dat_end', models.DateField(blank=True, null=True)),
                ('dat_created', models.DateField(auto_now=True)),
                ('dat_approved', models.DateTimeField(blank=True, null=True)),
                ('dbl_taken', models.FloatField(default=0)),
                ('int_active', models.IntegerField(default=0)),
                ('fk_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWorks.modelproject')),
                ('fk_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWorks.modelworktypes')),
                ('fk_work_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWorks.modelworkstatus')),
            ],
        ),
    ]
