# Generated by Django 3.1.2 on 2020-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Dispached', 'Dispached'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Ordered', max_length=120),
        ),
    ]
