# Generated by Django 3.1.2 on 2020-11-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_name', models.CharField(max_length=150, unique=True)),
                ('ram', models.CharField(max_length=50)),
                ('internal', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('screensize', models.CharField(max_length=120)),
                ('processor', models.CharField(max_length=120)),
                ('price', models.IntegerField(default=1500)),
                ('image', models.ImageField(upload_to='images')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.brand')),
            ],
        ),
    ]
